In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
font = {'family':'IPAexGothic'}
plt.rc('font', **font)

### 単純パーセプトロン

In [2]:
def step(x):
    x[x>0]=1
    x[x<=0]=0
    return x

In [3]:
step(np.array([-10, -5, 0, 5, 10,15]))

array([0, 0, 0, 1, 1, 1])

In [4]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
print(X)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]


AND論理ゲート

In [5]:
def AND(x):
    w = np.array([3,3])
    b = -5
    f = np.dot(x,w)+b
    y = step(f)
    return y

In [8]:
AND(X)

array([0, 0, 0, 1])

In [7]:
def OR(x):
    w = np.array([3,3])
    b = -2
    f = np.dot(x,w)+b
    y = step(f)
    return y

In [9]:
OR(X)

array([0, 1, 1, 1])

In [10]:
def NOT(x):
    w = -3
    b = 1
    f = np.dot(x,w)+b
    y = step(f)
    return y

In [11]:
X = np.array([[0],[1]])
NOT(X)

array([[1],
       [0]])

### 隠れ層を増やす

In [12]:
def XOR(x):
    y1 = AND(x)
    y2 = NOT(y1)
    y3 = OR(x)
    y4 = np.c_[y2,y3]
    y5 = AND(y4)
    return y5

In [13]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
XOR(X)

array([0, 1, 1, 0])

XORをニューラルネットワークで実装

In [14]:
input_size = 2
hidden_size = 4
output_size = 1

In [16]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

In [17]:
m = X.shape[0]

In [1]:
def sigmoid(x):
    y = 1/(1+np.exp(-x))
    return y

$\sigma^{'}(x)=\sigma(x)(1-\sigma(x))$

In [ ]:
aa